FROM ubuntu:latest

RUN apt-get update  && apt-get install tzdata && apt-get install python3 python3-pip tzdata nodejs npm -y

RUN pip3 install flask flask_sqlalchemy flask_migrate 

WORKDIR /app

COPY . /app

CMD ["python", "server.py"]